name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test --enable-code-coverage
    - name: Convert coverage report
      run: xcrun llvm-cov export -format="lcov" .build/debug/OTPKitPackageTests.xctest/Contents/MacOS/OTPKitPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
